ViewModels/CommentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyWebApp.ViewModels
{
    public class CommentViewModel
    {
        [Required]
        public string Text { get; set; }
        public DateTime AddingTime { get; set; }
        public string AuthorName { get; set; }
        public int ProblemId { get; set; }
    }
}

ViewModels/ProblemViewModels.cs
using System.Web;
using MyWebApp.Repositories;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using MyWebApp.Models;
using System.Web.Mvc;
using MyWebApp.ValidationAttributes;

namespace MyWebApp.ViewModels
{
    public class ProblemViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [AllowHtml]
        public string Text { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        [CorrectSetOfAnswers]
        public string Answers { get; set; }

        public string TagsString { get; set; }

        public ICollection<string> Tags { get; set; }
        public ICollection<string> Images { get; set; }
        public ICollection<string> Videos { get; set; }

        public int Id { get; set; }
        public bool Solved { get; set; }

        public int Likes { get; set; }
        public int Dislikes { get; set; }

        public string Category{ get; set; }

        public List<CommentViewModel> Comments { get; set; }
        private readonly List<Category> _categories = new CategoryRepository(new ApplicationDbContext()).Get().ToList();

        public HttpPostedFileBase MyFile { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int SelectedCategoryId { get; set; }

        public IEnumerable<SelectListItem> Categories
        {
            get { return new SelectList(_categories, "Id", "Name"); }
        }
    }
}

Controllers/ProblemController.cs
using System.IO;
using System.Threading;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.Ajax.Utilities;
using Microsoft.Owin.Security.Provider;
using MyWebApp.Filters;
using MyWebApp.Helpers;
using MyWebApp.Models;
using MyWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MyWebApp.Repositories.Interfaces;
using System.Collections.ObjectModel;
using MarkdownDeep;

namespace MyWebApp.Controllers
{
    [Culture]
    public class ProblemController : Controller
    {

        private readonly IProblemRepository problemRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IAnswerRepository answerRepository;
        private readonly IUserSolvedRepository userSolvedRepository;
        private readonly IUserAttemptedRepository userAttemptedRepository;
        private readonly IImageRepository imageRepository;
        private readonly ITagRepository tagRepository;
        private readonly ILikeRepository likeRepository;
        private readonly IDislikeRepository dislikeRepository;
        private readonly ICommentRepository commentRepository;

        public ProblemController(IProblemRepository problemRepository, ICategoryRepository categoryRepository, IAnswerRepository answerRepository, IUserSolvedRepository userSolvedRepository, IUserAttemptedRepository userAttemptedRepository, IImageRepository imageRepository, ITagRepository tagRepository, ILikeRepository likeRepository, IDislikeRepository dislikeRepository, ICommentRepository commentRepository)
        {
            this.problemRepository = problemRepository;
            this.categoryRepository = categoryRepository;
            this.answerRepository = answerRepository;
            this.userAttemptedRepository = userAttemptedRepository;
            this.userSolvedRepository = userSolvedRepository;
            this.tagRepository = tagRepository;
            this.imageRepository = imageRepository;
            this.likeRepository = likeRepository;
            this.dislikeRepository = dislikeRepository;
            this.commentRepository = commentRepository;
        }

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            return View(problemRepository.Get());
        }

        [HttpGet]
        public ActionResult Show(int ?id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Problem problem = problemRepository.GetByID(id);

            var md = new Markdown();
            problem.Text = md.Transform(problem.Text);

            IEnumerable<UserSolvedProblem> usersSolved = userSolvedRepository.Get(m => m.ProblemId == problem.Id);
            IEnumerable<UserSolvedProblem> userProblem =
                from userSolution in usersSolved
                where userSolution.User.UserName == User.Identity.Name
                select userSolution;

            //usersSolved.Contains()
            var pvm = GlobalHelper.GetShowProblemViewModel(problem);
            pvm.IsSolved = userProblem.Count() != 0;
            pvm.Answers = "";
            return View(pvm);
        }


        [HttpPost]
        [Authorize]
        public ActionResult Show(ShowProblemViewModel problemView)//Actually it's Solve method.
        {
            if (problemView.Author == User.Identity.Name)
            {
                problemView.Answers = "";
                return View(problemView);

            }

            Problem problem = problemRepository.GetByID(problemView.Id);
            var pvm = GlobalHelper.GetShowProblemViewModel(problem);
            pvm.IsSolved = false;
            if (ModelState.IsValidField("Answers"))
                if (GlobalHelper.AreEqual(GetAnswersFromString(problemView.Answers, problem), problem.CorrectAnswers))
                {
                    userSolvedRepository.Insert(new UserSolvedProblem { UserId = UserManager.FindByName(User.Identity.Name).Id, ProblemId = problem.Id });
                    var user = UserManager.FindByName(User.Identity.Name);
                    int attempts= (from attempt in user.AttemptedProblems
                                       where attempt.User==user
                                       select attempt).Count();
                    double rating = 100;
                    for (int i = 0; i < attempts; i++)
                        rating *= 0.95;

                    user.Rating += (int)rating;
                    UserManager.Update(user);
                    pvm.IsSolved = true;
                }
                else
                {
                    userAttemptedRepository.Insert(new UserAttemptedProblem { UserId = UserManager.FindByName(User.Identity.Name).Id, ProblemId = problem.Id });
                }


            var md = new Markdown();

            problem.Text = md.Transform(problem.Text);

            return View(pvm);
        }

        public ActionResult Tutorial()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Button = "Create";
            return View(new EditProblemViewModel { TagsString = "" });
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(EditProblemViewModel problemView)
        {
            if (ModelState.IsValidField("Answers"))
                AddProblemFromView(problemView);
            else
                return View(problemView);

            problemView.Author = User.Identity.Name;
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            
            ViewBag.Button = "Edit";
            Problem problem = problemRepository.GetByID(id);

            if (problem.Author.UserName != User.Identity.Name && !User.IsInRole("admin"))
            {
                return RedirectToAction("Index");
            }

            var pvm = GlobalHelper.GetEditProblemViewModel(problem);
      
            return View(pvm);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Edit(EditProblemViewModel problemView)
        {
            if (ModelState.IsValidField("Answers"))
                UpdateProblemFromView(problemView);
            else
                return View(problemView);

            problemView.Author = User.Identity.Name;
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public JsonResult Like(int problemId)
        {
            Problem problem = problemRepository.GetByID(problemId);

            
            var likes = problem.Likes.Count;
            var dislikes = problem.Dislikes.Count;

            if (problem.Author.UserName == User.Identity.Name)
                return Json(new { l = likes, d = dislikes });

            bool haslike = likeRepository.Get().Where(m => m.ProblemId == problemId).Count(m => m.User.UserName == User.Identity.Name) != 0;
            bool hasdislike = dislikeRepository.Get().Where(m => m.ProblemId == problemId).Count(m => m.User.UserName == User.Identity.Name) != 0;

            int dislikeId = 0;
            int likeId = 0;

            if (haslike) likeId = likeRepository.Get().Where(m => m.ProblemId == problemId).First(m => m.User.UserName == User.Identity.Name).Id;
            if (hasdislike) dislikeId = dislikeRepository.Get().Where(m => m.ProblemId == problemId).First(m => m.User.UserName == User.Identity.Name).Id;

            if (haslike)
            {
                likeRepository.Delete(likeId);
                likes--;
            }
            else
            {
                if (hasdislike)
                {
                    likeRepository.Insert(new Like { UserId = UserManager.FindByName(User.Identity.Name).Id, ProblemId = problemId });
                    dislikeRepository.Delete(dislikeId);
                    dislikes--;
                    likes++;
                }
                else
                {
                    likeRepository.Insert(new Like { UserId = UserManager.FindByName(User.Identity.Name).Id, ProblemId = problemId });
                    likes++;
                }
            }

            return Json(new { l = likes, d = dislikes });

        }

        [HttpPost]
        [Authorize]
        public JsonResult Dislike(int problemId)
        {
            Problem problem = problemRepository.GetByID(problemId);
            var likes = problem.Likes.Count;
            var dislikes = problem.Dislikes.Count;

            if (problem.Author.UserName == User.Identity.Name)
                return Json(new { l = likes, d = dislikes });

            bool haslike = likeRepository.Get().Where(m => m.ProblemId == problemId).Count(m => m.User.UserName == User.Identity.Name) != 0;
            bool hasdislike = dislikeRepository.Get().Where(m => m.ProblemId == problemId).Count(m => m.User.UserName == User.Identity.Name) != 0;

            int dislikeId = 0;
            int likeId = 0;

            if (haslike) likeId = likeRepository.Get().Where(m => m.ProblemId == problemId).First(m => m.User.UserName == User.Identity.Name).Id;
            if (hasdislike) dislikeId = dislikeRepository.Get().Where(m => m.ProblemId == problemId).First(m => m.User.UserName == User.Identity.Name).Id;

            if (hasdislike)
            {
                dislikeRepository.Delete(dislikeId);
                dislikes--;
            }
            else
            {
                if (haslike)

Views/Problem/Create.cshtml
@model MyWebApp.ViewModels.EditProblemViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form action="/Problem/UploadFile" method="post" enctype="multipart/form-data" id="imageform"></form>

@using (Html.BeginForm("Create"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        @Html.Partial("_CreateEdit", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="create" type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Problem/Edit.cshtml
@model MyWebApp.ViewModels.EditProblemViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form action="/Problem/UploadFile" method="post" enctype="multipart/form-data" id="imageform"></form>

@using (Html.BeginForm("Edit"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.Partial("_CreateEdit", Model)

        <div class="form-group">
        @Html.LabelFor(model => model.IsBlocked, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsBlocked, new { @class = "form-control" })
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="edit" type="submit" value="Edit" class="btn btn-default " />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Problem/Index.cshtml
@model IEnumerable<MyWebApp.Models.Problem>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <div class="jumbotron">

        <table title="Problems" class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>Problem</th>
                    <th>Author</th>
                    <th>Category</th>
                    <th>Rating</th>
                    <th>Solved</th>
                    <th>Blocked</th>
                </tr>
            </thead>
            @foreach (var problem in Model)
            {
                <tr>
                    <th>
                        @Html.ActionLink(problem.Name, "Show", "Problem", new { id = problem.Id },null)
                    </th>
                    <th>
                        @problem.Author.UserName
                    </th>
                    <th>
                        @problem.Category.Name
                    </th>
                    <th>
                        @(@problem.Likes.Count()-@problem.Dislikes.Count())
                    </th>
                    <th>
                        @problem.UsersWhoSolved.Count()
                    </th>
                    <th>
                        @problem.IsBlocked
                    </th>
                    
                </tr>
            }
        </table>
        @Html.ActionLink("Create","Create","Problem")
    </div>

Views/Problem/Show.cshtml
@model MyWebApp.ViewModels.ShowProblemViewModel
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-2.1.1.js"></script>
<link href="~/Content/bootstrap-tagsinput.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-tagsinput.js"></script>
<h1 id="title">@Model.Name</h1>
<div class="row">
    <div class="col-md-7">
        @Html.Markdown(@Model.Text)

        @Html.Hidden("problemId", @Model.Id, new { @id = "problemId" })

    </div>
    <div class="col-md-5 ">
        <div class="row">
            <div class="container col-md-2">
                <a class="btn btn-warning">@Model.Category</a>
            </div>
            @if (User.Identity.Name == Model.Author || User.IsInRole("admin"))
            {
                <div class="container col-md-2">
                    @Html.ActionLink("Edit", "Edit", "Problem", new { id = Model.Id }, new { @class = "btn btn-success" })
                </div>
            }
        </div>

        <br />
        <div class="container">
            @Html.TextBoxFor(model => model.TagsString, new Dictionary<string, object> { { "data-role", "tagsinput" }, { "type", "text" }, { "readonly", "" }, { "hidden", "" }, { "style", "maxheight:50px" } })
        </div>
        @if (Model.IsSolved != true && Model.Author != User.Identity.Name && User.Identity.IsAuthenticated && !Model.IsBlocked)
        {
            <div class="well">
                @using (Html.BeginForm("Show", "Problem"))
                {

                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Answers, "Your answer", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Answers, new { htmlAttributes = new { @class = "form-control", @id = "answers" } })
                                @Html.ValidationMessageFor(model => model.Answers, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(model => model.Id)
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Send solution" class="btn btn-default" />
                            </div>
                        </div>

                    </div>
                }
            </div>
        }
        else if(Model.IsSolved)
        {
            <div class="well"> You solved it!</div>
        }
        <br />

        <a id="like" class="btn btn-success">Like <span class="badge" id="likeCount">@Model.Likes</span></a>
        <a id="dislike" class="btn btn-danger">Dislike <span class="badge" id="dislikeCount">@Model.Dislikes</span></a>


    </div>
</div>
@if (User.Identity.IsAuthenticated && !Model.IsBlocked)
{
    <div class="jumbotron">
        <textarea id="commentTextBox" placeholder="Your comment" style="width: 60%"></textarea>
        <br />
        <a id="addComment" class="btn btn-success">Add comment</a>
    </div>
}
<legend>Comments:</legend>
<hr/>
<div id="comments" style="width:60%">
    @foreach (var comment in Model.Comments)
    {
        @Html.Partial("_CommentView", comment)
    }
</div>
<script src="/Scripts/problemShowScript.js"></script>

Views/Problem/Tutorial.cshtml
@{
    ViewBag.Title = "Tutorial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tutorial</h2>
<hr/>
<p>
    <img src="~/Resources/1.png" width="600" height="300" />
    <h1 class="jumbotron">Go to the video page.</h1>
    <img src="~/Resources/2.png" width="600" height="300" />
    <h1 class="jumbotron">In context menu choose "Get embed code".</h1>
    <img src="~/Resources/3.png" width="600" height="300" />
    <h1 class="jumbotron">Copy text.</h1>
    <img src="~/Resources/4.png" width="600" height="300" />
    <h1 class="jumbotron">Paste it in Text field.</h1>
    <img src="~/Resources/5.png" width="600" height="300" />
    <h1 class="jumbotron">You're perfect!</h1>
</p>

Views/Problem/UploadImage.cshtml
<link href="~/Content/Upload.css" rel="stylesheet" />

<div>
    <div class="form-group">
        <label class="control-label col-md-2" for="myfile" form="imageform">Image: </label>
        <div class="col-md-10">
            <input type="file" id="myfile" name="myfile" form="imageform" accept="image/*" class="form-control" title="Choose image" data-classbutton="btn btn-success"><br>
        </div>
    </div>
    <input type="submit" value="Upload File to Server" form="imageform" >
</div>
<br/>
<div class="progress">
    <div class="progress-bar"></div>
</div>

<div class="row">
    <div class="col-md-2">URL for markdown:</div>
    <div class="col-md-2" id="status"></div>
</div>

<script src="http://malsup.github.com/jquery.form.js"></script>
<script src="~/Scripts/CreateEditScript.js"></script>

Views/Problem/_CommentView.cshtml
@model MyWebApp.ViewModels.CommentViewModel
<div class="row well">
    <div class="col-md-2">
        <div>
            @Model.AuthorName
        </div>
        <div>
            @Model.AddingTime
        </div>
    </div>

    <blockquote class="col-md-4">
        @Model.Text
    </blockquote>
</div>

Views/Problem/_CreateEdit.cshtml
@model MyWebApp.ViewModels.EditProblemViewModel

<script src="~/Scripts/jquery-2.1.1.js"></script>
<script src="~/Scripts/jquery-ui-1.9.2.min.js"></script>

<link href="~/Content/bootstrap-tagsinput.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-tagsinput.js"></script>
@Scripts.Render("~/bundles/typeahead")

<script src="http://malsup.github.com/jquery.form.js"></script>
<script src="~/Scripts/CreateEditScript.js"></script>

<ul class="nav nav-tabs" style="margin-bottom: 15px;">
    <li class="active"><a href="#Main" data-toggle="tab">Requied info</a></li>
    <li class=""><a href="#media" data-toggle="tab">Photos&Videos</a></li>
    <li class=""><a href="#tags" data-toggle="tab">Tags</a></li>
</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="Main">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, 10, 10, new { data_provide = "markdown", id = "content", @style = "max-width:100%", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.SelectedCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedCategoryId, Model.Categories, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="media">
        <hr />
        <h1>Video</h1>
        <div> To insert video in your problem look <a href="/Problem/Tutorial">tutorial.</a></div>
        <hr />
        <h1>Images</h1>
        @Html.Partial("UploadImage")
    </div>

    <div class="tab-pane fade" id="tags">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.TagsString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="prefetch">
                    @Html.TextBoxFor(model => model.TagsString, new Dictionary<string, object> { { "class", "form-control" }, { "type", "text" }, { "data-role", "tagsinput" },{"id","taginput"} })
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/TagScript.js"></script>

<script src="~/Scripts/markdown.js"></script>
<script src="~/Scripts/to-markdown.js"></script>
<script src="~/Scripts/bootstrap-markdown.js"></script>
<link href="~/Content/bootstrap-markdown.min.css" rel="stylesheet" />