Controllers/AdminController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MyWebApp.Filters;
using MyWebApp.Repositories.Interfaces;
//
namespace MyWebApp.Controllers
{
    [Culture]
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
        private ApplicationUserManager _userManager;
        private readonly IProblemRepository problemRepository;
        public AdminController(IProblemRepository problemRepository)
        {
            this.problemRepository = problemRepository;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Problems()
        {
            return View(problemRepository.Get());
        }
        public ActionResult Users()
        {
            return View(UserManager.Users);
        }

        [HttpGet]
        public ActionResult DeleteProblem(int? id)
        {
            if (id != null)
            {
                problemRepository.Delete(id);
            }
            return RedirectToAction("Problems");
        }

        [HttpGet]
        public ActionResult LockUser(string id)
        {
            if (User.Identity.Name == UserManager.FindById(id).UserName)
                return RedirectToAction("Users");

            UserManager.FindById(id).IsBlocked = true;

            return RedirectToAction("Users");
        }
        [HttpGet]
        public ActionResult UnlockUser(string id)
        {
            if (User.Identity.Name == UserManager.FindById(id).UserName)
                return RedirectToAction("Users");

            UserManager.FindById(id).IsBlocked = false;
          
            return RedirectToAction("Users");
        }

        [HttpGet]
        public ActionResult ResetPassword(string id)
        {
            if (id != null)
            {
            }
            return RedirectToAction("Users");
        }

    }
}

Controllers/UserController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MyWebApp.Filters;
using MyWebApp.Repositories.Interfaces;

namespace MyWebApp.Controllers
{
    [Culture]
    public class UserController : Controller
    {
         private readonly IProblemRepository problemRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IAnswerRepository answerRepository;
        private readonly IUserSolvedRepository userSolvedRepository;
        private readonly IUserAttemptedRepository userAttemptedRepository;
        private readonly IImageRepository imageRepository;
        private readonly ITagRepository tagRepository;
        private readonly ILikeRepository likeRepository;
        private readonly IDislikeRepository dislikeRepository;
        private readonly ICommentRepository commentRepository;


        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        public UserController(IProblemRepository problemRepository, ICategoryRepository categoryRepository, IAnswerRepository answerRepository, IUserSolvedRepository userSolvedRepository, IUserAttemptedRepository userAttemptedRepository, IImageRepository imageRepository, ITagRepository tagRepository, ILikeRepository likeRepository, IDislikeRepository dislikeRepository, ICommentRepository commentRepository)
        {
            this.problemRepository = problemRepository;
            this.categoryRepository = categoryRepository;
            this.answerRepository = answerRepository;
            this.userAttemptedRepository = userAttemptedRepository;
            this.userSolvedRepository = userSolvedRepository;
            this.tagRepository = tagRepository;
            this.imageRepository = imageRepository;
            this.likeRepository = likeRepository;
            this.dislikeRepository = dislikeRepository;
            this.commentRepository = commentRepository;
        }
        // GET: User
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }

        public ActionResult Show(string id)
        {
            return View(UserManager.FindById(id));
        }

    }
}

Views/User/Index.cshtml
@model IEnumerable<MyWebApp.Models.ApplicationUser>
@{
    ViewBag.Title = "Users";
}
<div class="jumbotron">

    <table title="Users" class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>User</th>
                <th>Raiting</th>
            </tr>
        </thead>

        @foreach (var user in Model)
        {
            <tr>
                <th>
                    @Html.ActionLink(user.UserName, "Show", "User", new { id = user.Id }, null)
                </th>
                <th>
                    @user.Rating
                </th>
   
            </tr>
        }
    </table>
</div>

Views/User/Show.cshtml
@using Microsoft.AspNet.Identity
@model MyWebApp.Models.ApplicationUser
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.UserName</h2>
@if (Model.IsBlocked)
{
    <div class="alert alert-dismissable alert-warning">
        <h4>User blocked!</h4>
    </div>
}
else if(User.Identity.Name != Model.UserName && User.IsInRole("admin"))
{
    @Html.ActionLink("Lock", "LockUser", "Admin", new { id = Model.Id }, new{ @class="btn btn-danger"})

}
<div>
    <ul class="list-group">
        <li class="list-group-item">
            @Model.Email
        </li>
        <li class="list-group-item">
            <span class="badge">@Model.Rating</span>
            Rating
        </li>
    </ul>
</div>